dim swApp
dim storePath
dim docVisible
Private Const MAX_PATH = 260
'Directories only
Private Const BIF_RETURNONLYFSDIRS = &H1&
'Windows 2000 (Shell32.dll 5.0) extended dialog
Private Const BIF_NEWDIALOGSTYLE = &H40
' show edit box
Private Const BIF_EDITBOX = &H10&
' add all dir options
Private Const BIF_BrowseFolder = BIF_EDITBOX  Or BIF_RETURNONLYFSDIRS Or BIF_NEWDIALOGSTYLE
' set the virtual desktop as  ini folder 
Private Const IniFolder = &H0 'Virtual Desktop
Function getLastFeatureByType(model,typ)  
  Set feat = model.FirstFeature ' Get the 1st feature in part
  Set res = Nothing
  Count = 0
  Do While Not feat Is Nothing ' While we have a valid feature
    If feat.GetTypeName() = typ Then
      Set res = feat
    End If
    Set feat = feat.GetNextFeature() ' Get the next feature
  Loop ' Continue until no more
  Set getLastFeatureByType = res
End Function
' this code with copy a matrix to a other
Function copyMat4x4(source)
Dim res(0 To 15) As Double
For i = 0 To 15
 res(i) = source(i)
Next
copyMat4x4 = res
End Function

' This code creates a mat from a sw mat
Function createMatFromSWMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = 0
 res(4) = source(3)
 res(5) = source(4)
 res(6) = source(5)
 res(7) = 0
 res(8) = source(6)
 res(9) = source(7)
 res(10) = source(8)
 res(11) = 0
 res(12) = source(9)
 res(13) = source(10)
 res(14) = source(11)
 res(15) = source(12)
 createMatFromSWMat = res
End Function
Function createSWMatFromMat(source)
 Dim res(0 To 15) As Double
 res(0) = source(0)
 res(1) = source(1)
 res(2) = source(2)
 res(3) = source(4)
 res(4) = source(5)
 res(5) = source(6)
 res(6) = source(8)
 res(7) = source(9)
 res(8) = source(10)
 res(9) = source(12)
 res(10) = source(13)
 res(11) = source(14)
 res(12) = source(15)
 res(13) = 0
 res(14) = 0
 res(15) = 0
 createSWMatFromMat = res
End Function
Function createMat4x4FromValues(x1,x2,x3,y1,y2,y3,z1,z2,z3,t1,t2,t3)
 Dim res(0 To 15) As Double
 res(0) = x1
 res(1) = x2
 res(2) = x3
 res(3) = 0
 res(4) = y1
 res(5) = y2
 res(6) = y3
 res(7) = 0
 res(8) = z1
 res(9) = z2
 res(10) =z3
 res(11) = 0
 res(12) = t1
 res(13) = t2
 res(14) = t3
 res(15) = 1
 createMat4x4FromValues = res
End Function
' this code will mult a common mat with any other stuff
Function multMatMat(ld, xld, yld, rd, xrd, yrd)
  mulRes = yld * xrd
  'Dim od(0 To 0) As Variant
  ReDim od(mulRes - 1) As Double
  For i = 0 To mulRes - 1
   od(i) = 0#
  Next
  y = 0
  While y < yld
    x = 0
    While x < xrd
      i = 0
      While i < xld
       od(x * yld + y) = od(x * yld + y) + ld(i * yld + y) * rd(x * yrd + i)
       i = i + 1
      Wend
      x = x + 1
    Wend
    y = y + 1
  Wend
  multMatMat = od

End Function
' this code will mult a vector with a matrix
Function mulMat4x4Values3d(mat, x,y,z)
  tmp = createVec4d(x, y, z, 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Values3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Vec3d(mat, vec)
  tmp = createVec4d(vec(0), vec(1), vec(2), 1)
  res = multMatMat(mat, 4, 4, tmp, 1, 3)
  mulMat4x4Vec3d = createVec3d(res(0), res(1), res(2))
End Function
Function mulMat4x4Mat4x4(mat1, mat2)
  mulMat4x4Mat4x4 = multMatMat(mat1, 4, 4, mat2, 4, 4)
End Function
' create a 4x4 matrix
Function createMat4x4()
 Dim res(0 To 15) As Double
 for i = 0 to 15 
 res(i) = 0
 next
 createMat4x4 = res
End Function
Function createMat4x4Ident()
 Dim res(0 To 15) As Double
 res(0) = 1
 res(5) = 1
 res(10) = 1
 res(15) = 1
 res(1) = 0
 res(2) = 0
 res(3) = 0
 res(4) = 0
 res(6) = 0
 res(7) = 0
 res(8) = 0
 res(9) = 0
 res(11) = 0
 res(12) = 0
 res(13) = 0
 res(14) = 0
 createMat4x4Ident = res
End Function
' this function create a new vector
Function createVec3d(x, y, z)
 Dim res(0 To 2) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 createVec3d = res
End Function
' this function create a new vector
Function createVec4d(x, y, z, w)
 Dim res(0 To 3) As Double
 res(0) = x
 res(1) = y
 res(2) = z
 res(3) = w
 createVec4d = res
End Function

Function getMatTVec(mat)
 getMatTVec = createVec3d(mat(12), mat(13), mat(14))
End Function

Sub setMatTVec(mat, v)
 mat(12) = v(0)
 mat(13) = v(1)
 mat(14) = v(2)
End Sub
Sub setMatXVec(mat, v)
 mat(0) = v(0)
 mat(1) = v(1)
 mat(2) = v(2)
End Sub
Sub setMatYVec(mat, v)
 mat(4) = v(0)
 mat(5) = v(1)
 mat(6) = v(2)
End Sub
Sub setMatZVec(mat, v)
 mat(8) = v(0)
 mat(9) = v(1)
 mat(10) = v(2)
End Sub
Sub setMatScale(mat, s)
 mat(15) = s
End Sub
Function getMatXVec(mat)
 getMatXVec = createVec3d(mat(0), mat(1), mat(2))
End Function
Function getMatYVec(mat)
 getMatYVec = createVec3d(mat(4), mat(5), mat(6))
End Function
Function getMatZVec(mat)
 getMatZVec = createVec3d(mat(8), mat(9), mat(10))
End Function

Function negVec3d(v)
 negVec3d = createVec3d(-v(0), -v(1), -v(2))
End Function
Function scaleVec3d(v,s)
 scaleVec3d = createVec3d(v(0)*s,v(1)*s,v(2)*s)
End Function
' invert a 4x4 matrix
Function invMat4x4(source)
target = copyMat4x4(source)
setMatTVec target, createVec3d(0, 0, 0)
 target(1) = source(4)
 target(4) = source(1)
 target(2) = source(8)
 target(8) = source(2)
 target(6) = source(9)
 target(9) = source(6)
 setMatScale target,1
 t = getMatTVec(source)
 v = mulMat4x4Vec3d(target, t)
 setMatTVec target, negVec3d(v)
 invMat4x4 = target
End Function
Function IsEqual(argVec3DA, argVec3DB)
  For i = 0 To 2
    If( argVec3DA(i) <> argVec3DB(i) ) Then
      Exit For
    End If
  Next
  If(i = 3) Then
    IsEqual = 1
  Else
    IsEqual = 0
  End If
End Function
Function getFaceFromModel(part, pos, normal)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   found = 0
   Dim body As Object
   Set body = partBodies(k)
   Set face = body.GetFirstFace()
   Set getFaceFromModel = nothing
   minDist = -1
   Do While Not face Is Nothing ' While we have a valid feature
     Set sur = face.GetSurface()
     If sur.IsPlane() Then
       planePara = sur.PlaneParams
       faceNormal = face.normal
       nTest = faceNormal(0) * normal(0) + faceNormal(1) * normal(1) + faceNormal(2) * normal(2)
       If nTest > 1 - 0.000001 Then
         ' check projection
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If ( dTest < minDist Or minDist = -1 ) Then
           Set getFaceFromModel = face
           minDist = dTest
           found=1
         End If
       End If
     else
       If sur.IsCylinder() then
         closeRes = face.GetClosestPointOn(pos(0), pos(1), pos(2))
         dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
         If ( dTest < minDist Or minDist = -1 ) Then
           res=sur.EvaluateAtPoint(closeRes(0),closeRes(1),closeRes(2))
           nTest=res(0)*normal(0)+res(1)*normal(1)+res(2)*normal(2)
           if nTest>1-0.00000001 then
             Set getFaceFromModel = face
             found=1
           End if
         End if
       End if
     End if
     Set face = face.GetNextFace ' Get the next Face
   Loop
   If (found = 1) Then
     Exit For
   End If
 Next k
End Function
Function getEdgeFromModel(part, pos,byref edgeRet)
 Dim partBodies As Variant
 partBodies = part.GetBodies(swSolidBody)
 For k = LBound(partBodies) To UBound(partBodies)
   Dim body As Object
   Set body = partBodies(k)
   edges= body.GetEdges()
   start= LBound(edges)
   ende = UBound(edges)
   For i = start To ende
     Set edge = edges(i)
     closeRes=edge.GetClosestPointOn(pos(0),pos(1),pos(2))
     dTest = (pos(0) - closeRes(0)) * (pos(0) - closeRes(0)) + (pos(1) - closeRes(1)) * (pos(1) - closeRes(1)) + (pos(2) - closeRes(2)) * (pos(2) - closeRes(2))
     If dTest < 0.00000001 Then
       set edgeRet=edge
       getEdgeFromModel=true
       exit function
     End If
   Next i
 Next k
 getEdgeFromModel=false
End Function
sub cLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.SketchManager.CreateLine pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cCLn(part,wMat,x1,y1,x2,y2)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
Part.CreateCenterLineVB pk1(0),pk1(1),0,pk2(0),pk2(1),0
end sub
sub cArc(part,wMat,x1,y1,x2,y2,x3,y3)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
pk2=mulMat4x4Values3d(wMat,x2,y2,0)
pk3=mulMat4x4Values3d(wMat,x3,y3,0)
Part.SketchManager.Create3PointArc pk1(0),pk1(1),0,pk3(0),pk3(1),0,pk2(0),pk2(1),0
end sub
sub cCir(part,wMat,x1,y1,rad)
pk1=mulMat4x4Values3d(wMat,x1,y1,0)
Part.SketchManager.CreateCircleByRadius pk1(0),pk1(1),0,rad
end sub
Public Function  BrowseForFolder
Dim objFolder, objShell
Set objShell = CreateObject("Shell.Application")
Set objFolder = objShell.BrowseForFolder(0, "Please select the folder..", BIF_BrowseFolder, IniFolder)
If Not (objFolder Is Nothing) Then
		BrowseForFolder = objFolder.Self.path
End If
End Function
Sub SelectCommonEdge(argFaceA, argFaceB)
  edgesA = argFaceA.GetEdges
  edgesB = argFaceB.GetEdges
  For Each edgeA In edgesA
    Set vertexA1 = edgeA.GetStartVertex
    Set vertexA2 = edgeA.GetEndVertex
    pointA1 = vertexA1.GetPoint
    pointA2 = vertexA2.GetPoint
    For Each edgeB In edgesB
      Set vertexB1 = edgeB.GetStartVertex
      Set vertexB2 = edgeB.GetEndVertex
      pointB1 = vertexB1.GetPoint
      pointB2 = vertexB2.GetPoint
      If ( (IsEqual(pointA1, pointB1) And IsEqual(pointA2, pointB2)) Or (IsEqual(pointA1, pointB2) And IsEqual(pointA2, pointB1)) ) Then
        edgeA.Select(True)
        Exit Sub
      End If
    Next
  Next
End Sub
Sub CreatePart0
dim errors as long
dim warnings as long
Dim longstatus As Long
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set res=swApp.OpenDoc6 ( storePath & "536393 ADN-10-P---(Z).sldprt",1,3,"", errors, warnings)
swApp.ActivateDoc2 "536393 ADN-10-P---(Z).sldprt", False, longstatus
if not res is nothing then
 if (docVisible=0) then
  swApp.DocumentVisible 1, 1
 end if
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
Dim sPartTemplateName As String
sPartTemplateName = swApp.GetUserPreferenceStringValue(8)
Set part = swApp.NewDocument(sPartTemplateName, 0, 0, 0)
swApp.ActivateDoc2 "536393 ADN-10-P---(Z).sldprt", False, longstatus
Set part = swApp.ActiveDoc
part.SketchManager.AddToDB = true
part.SketchManager.DisplayWhenAdded = false
part.ActiveView.EnableGraphicsUpdate = false
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NB", 30, "536393 ADN-10-P---(Z)"
customPropMgr.Add2 "NN", 30, "ADN-(Z)"
customPropMgr.Add2 "NT", 30, "Compact cylinder - Z"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $AUSF.-$HUB.-$DF.$QN.$S2N.$S1S20N.$R8N.$TTN.$R3N.---(Z)"
customPropMgr.Add2 "LINA", 30, "536393 ADN-10-P---(Z)"
customPropMgr.Add2 "CATALOG", 30, "Festo"
customPropMgr.Add2 "TNR", 30, "536393"
customPropMgr.Add2 "AUSF", 30, "ADN"
customPropMgr.Add2 "KDM", 30, "125"
customPropMgr.Add2 "BG", 30, "20.000"
customPropMgr.Add2 "HUB", 30, "10.00000"
customPropMgr.Add2 "DF", 30, "P"
customPropMgr.Add2 "GA", 30, "A"
customPropMgr.Add2 "Q", 30, "-"
customPropMgr.Add2 "S2S20", 30, "-"
customPropMgr.Add2 "S1", 30, "-"
customPropMgr.Add2 "R8", 30, "-"
customPropMgr.Add2 "TT", 30, "-"
customPropMgr.Add2 "R3", 30, "-"
customPropMgr.Add2 "A", 30, "40.000"
customPropMgr.Add2 "A1", 30, "0.000"
customPropMgr.Add2 "AF", 30, "25.000"
customPropMgr.Add2 "AF1", 30, "12.000"
customPropMgr.Add2 "AF2", 30, "24.000"
customPropMgr.Add2 "AF3", 30, "0.000"
customPropMgr.Add2 "B", 30, "0.000"
customPropMgr.Add2 "B1", 30, "0.000"
customPropMgr.Add2 "BG1", 30, "0.000"
customPropMgr.Add2 "D1", 30, "12.000"
customPropMgr.Add2 "D2", 30, "0.000"
customPropMgr.Add2 "D3", 30, "10.100"
customPropMgr.Add2 "D4", 30, "0.000"
customPropMgr.Add2 "D5", 30, "0.000"
customPropMgr.Add2 "D6", 30, "-"
customPropMgr.Add2 "D7", 30, "0.000"
customPropMgr.Add2 "D8", 30, "11.700"
customPropMgr.Add2 "D9", 30, "0.000"
customPropMgr.Add2 "E", 30, "134.600"
customPropMgr.Add2 "EE", 30, "G1/4"
customPropMgr.Add2 "EE1", 30, "-"
customPropMgr.Add2 "J", 30, "20.000"
customPropMgr.Add2 "J1", 30, "21.150"
customPropMgr.Add2 "J2", 30, "0.000"
customPropMgr.Add2 "KF", 30, "5/8-18 UNF-2B"
customPropMgr.Add2 "KF1", 30, "G1/4"
customPropMgr.Add2 "KF2", 30, "1/2-20 UNF-2B"
customPropMgr.Add2 "KF3", 30, "-"
customPropMgr.Add2 "KK", 30, "3/4-16 UNF-2A"
customPropMgr.Add2 "KK1", 30, "-"
customPropMgr.Add2 "L1", 30, "7.000"
customPropMgr.Add2 "L2", 30, "81.000"
customPropMgr.Add2 "L3", 30, "2.600"
customPropMgr.Add2 "L4", 30, "0.000"
customPropMgr.Add2 "L5", 30, "0.000"
customPropMgr.Add2 "L6", 30, "0.000"
customPropMgr.Add2 "L7", 30, "0.000"
customPropMgr.Add2 "L8", 30, "0.000"
customPropMgr.Add2 "L9", 30, "6.100"
customPropMgr.Add2 "L10", 30, "0.000"
customPropMgr.Add2 "L11", 30, "0.000"
customPropMgr.Add2 "MF", 30, "0.000"
customPropMgr.Add2 "MM", 30, "25.000"
customPropMgr.Add2 "MM1", 30, "0.000"
customPropMgr.Add2 "PL", 30, "10.500"
customPropMgr.Add2 "RT", 30, "M12"
customPropMgr.Add2 "RTNK", 30, "10.106"
customPropMgr.Add2 "SF", 30, "7/8"
customPropMgr.Add2 "SF1", 30, "-"
customPropMgr.Add2 "SW", 30, "20.000"
customPropMgr.Add2 "TG", 30, "110.000"
customPropMgr.Add2 "VD", 30, "0.000"
customPropMgr.Add2 "VD1", 30, "0.000"
customPropMgr.Add2 "WH", 30, "11.000"
customPropMgr.Add2 "WH1", 30, "0.000"
customPropMgr.Add2 "WL", 30, "9.000"
customPropMgr.Add2 "WL1", 30, "0.000"
customPropMgr.Add2 "Y1", 30, "0.500"
customPropMgr.Add2 "Y2", 30, "0.000"
customPropMgr.Add2 "ZJ", 30, "92.000"
customPropMgr.Add2 "ZM", 30, "103.000"
customPropMgr.Add2 "RU", 30, "124.600"
customPropMgr.Add2 "R1", 30, "23.600"
customPropMgr.Add2 "R2", 30, "1.920"
customPropMgr.Add2 "RA", 30, "48.600"
customPropMgr.Add2 "DSK", 30, "15.000"
customPropMgr.Add2 "MDK", 30, "18.000"
customPropMgr.Add2 "MK", 30, "12.000"
customPropMgr.Add2 "MT", 30, "6.000"
customPropMgr.Add2 "MS", 30, "10.000"
customPropMgr.Add2 "RUB", 30, "1.000"
customPropMgr.Add2 "B111", 30, "0.000"
customPropMgr.Add2 "B11", 30, "0.000"
customPropMgr.Add2 "B2", 30, "0.000"
customPropMgr.Add2 "B3", 30, "0.000"
customPropMgr.Add2 "B4", 30, "0.000"
customPropMgr.Add2 "B5", 30, "0.000"
customPropMgr.Add2 "B6", 30, "0.000"
customPropMgr.Add2 "B7", 30, "0.000"
customPropMgr.Add2 "B8", 30, "0.000"
customPropMgr.Add2 "B9", 30, "0.000"
customPropMgr.Add2 "B10", 30, "0.000"
customPropMgr.Add2 "W", 30, "0.000"
customPropMgr.Add2 "S", 30, "0.000"
customPropMgr.Add2 "LA", 30, "0.000"
customPropMgr.Add2 "LA1", 30, "0.000"
customPropMgr.Add2 "LA2", 30, "13.000"
customPropMgr.Add2 "LA3", 30, "27.800"
customPropMgr.Add2 "LA31", 30, "27.800"
customPropMgr.Add2 "LA4", 30, "0.000"
customPropMgr.Add2 "LA5", 30, "0.000"
customPropMgr.Add2 "LA6", 30, "0.000"
customPropMgr.Add2 "RR", 30, "11.000"
customPropMgr.Add2 "LA7", 30, "117.000"
customPropMgr.Add2 "LA8", 30, "78.000"
customPropMgr.Add2 "LA9", 30, "14.500"
customPropMgr.Add2 "LA10", 30, "9.000"
customPropMgr.Add2 "ES", 30, "6.860"
customPropMgr.Add2 "SS", 30, "6.000"
customPropMgr.Add2 "TS", 30, "4.000"
customPropMgr.Add2 "WS", 30, "0.800"
customPropMgr.Add2 "DK", 30, "13.000"
customPropMgr.Add2 "KS", 30, "8.000"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "536393 ADN-10-P---(Z)"
customPropMgr.Add2 "BOMINFO", 30, "536393 ADN-10-P---(Z)"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
customPropMgr.Add2 "IsFastener", 30, "0"
part.SummaryInfo(0)="536393 ADN-10-P---(Z)"
part.SummaryInfo(4)="Compact cylinder - Z"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75
valRGB(1)=0.75
valRGB(2)=0.75
valRGB(7)=0
part.MaterialPropertyValues=valRGB
Dim featMgr as object
set featMgr = part.FeatureManager
codeBag0 part,featMgr
codeBag14 part,featMgr
codeBag28 part,featMgr
part.ActiveView.EnableGraphicsUpdate = true
part.SketchManager.DisplayWhenAdded = true
part.SketchManager.AddToDB = false
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "536393 ADN-10-P---(Z).sldprt",0,0,nothing,errors,warnings
End Sub
Sub CreatePart1
dim errors as long
dim warnings as long
Dim longstatus As Long
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set res=swApp.OpenDoc6 ( storePath & "536393 ADN-10-P-A_(KS).sldprt",1,3,"", errors, warnings)
swApp.ActivateDoc2 "536393 ADN-10-P-A_(KS).sldprt", False, longstatus
if not res is nothing then
 if (docVisible=0) then
  swApp.DocumentVisible 1, 1
 end if
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
Dim sPartTemplateName As String
sPartTemplateName = swApp.GetUserPreferenceStringValue(8)
Set part = swApp.NewDocument(sPartTemplateName, 0, 0, 0)
swApp.ActivateDoc2 "536393 ADN-10-P-A_(KS).sldprt", False, longstatus
Set part = swApp.ActiveDoc
part.SketchManager.AddToDB = true
part.SketchManager.DisplayWhenAdded = false
part.ActiveView.EnableGraphicsUpdate = false
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NB", 30, "536393 ADN-10-P-A_(KS)"
customPropMgr.Add2 "NN", 30, "ADN-(KS)"
customPropMgr.Add2 "NT", 30, "Compact cylinder - piston rod"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $AUSF.-$HUB.-$DF.-$TH.$QN.$S2N.$K2N.$K5T.$K8N.$K10N.$S1N.$TTN.$R8N._(KS)"
customPropMgr.Add2 "LINA", 30, "536393 ADN-10-P-A_(KS)"
customPropMgr.Add2 "CATALOG", 30, "Festo"
customPropMgr.Add2 "TNR", 30, "536393"
customPropMgr.Add2 "AUSF", 30, "ADN"
customPropMgr.Add2 "DF", 30, "P"
customPropMgr.Add2 "GA", 30, "A"
customPropMgr.Add2 "WHX", 30, "11.000"
customPropMgr.Add2 "WH0", 30, "11.000"
customPropMgr.Add2 "WH1", 30, "0.000"
customPropMgr.Add2 "WH2", 30, "0.000"
customPropMgr.Add2 "WH3", 30, "0.000"
customPropMgr.Add2 "WHX1", 30, "11.000"
customPropMgr.Add2 "WHX2", 30, "11.700"
customPropMgr.Add2 "WH", 30, "11.000"
customPropMgr.Add2 "ZM", 30, "104.400"
customPropMgr.Add2 "ZM2", 30, "0.000"
customPropMgr.Add2 "ZB", 30, "92.000"
customPropMgr.Add2 "ZB1", 30, "0.000"
customPropMgr.Add2 "ZB2", 30, "0.000"
customPropMgr.Add2 "ZB6", 30, "0.000"
customPropMgr.Add2 "ZA", 30, "81.000"
customPropMgr.Add2 "KDM", 30, "125"
customPropMgr.Add2 "HUBP", 30, "-"
customPropMgr.Add2 "HUB", 30, "10"
customPropMgr.Add2 "TH", 30, "A"
customPropMgr.Add2 "Q", 30, "-"
customPropMgr.Add2 "S2S20", 30, "-"
customPropMgr.Add2 "K2", 30, "0"
customPropMgr.Add2 "K5", 30, "-"
customPropMgr.Add2 "K8", 30, "0"
customPropMgr.Add2 "K10", 30, "-"
customPropMgr.Add2 "S1", 30, "-"
customPropMgr.Add2 "TT", 30, "-"
customPropMgr.Add2 "R8", 30, "-"
customPropMgr.Add2 "A", 30, "40.000"
customPropMgr.Add2 "A1", 30, "0.000"
customPropMgr.Add2 "AF", 30, "25.000"
customPropMgr.Add2 "AF1", 30, "12.000"
customPropMgr.Add2 "AF2", 30, "24.000"
customPropMgr.Add2 "AF3", 30, "0.000"
customPropMgr.Add2 "AF5", 30, "0.000"
customPropMgr.Add2 "AF7", 30, "0.000"
customPropMgr.Add2 "D8", 30, "11.700"
customPropMgr.Add2 "D9", 30, "0.000"
customPropMgr.Add2 "KF", 30, "M16"
customPropMgr.Add2 "KF1", 30, "-"
customPropMgr.Add2 "KF2", 30, "G1/4"
customPropMgr.Add2 "KF3", 30, "M12"
customPropMgr.Add2 "KF5", 30, "-"
customPropMgr.Add2 "KF7", 30, "-"
customPropMgr.Add2 "KK", 30, "M20X1.5"
customPropMgr.Add2 "KK1", 30, "-"
customPropMgr.Add2 "L2", 30, "81.000"
customPropMgr.Add2 "L8", 30, "0.000"
customPropMgr.Add2 "MM", 30, "25.000"
customPropMgr.Add2 "MM1", 30, "0.000"
customPropMgr.Add2 "PL", 30, "10.500"
customPropMgr.Add2 "SF", 30, "21"
customPropMgr.Add2 "SF1", 30, "0"
customPropMgr.Add2 "SF3", 30, "20.0"
customPropMgr.Add2 "WL", 30, "9.000"
customPropMgr.Add2 "WL1", 30, "0.000"
customPropMgr.Add2 "L101K5", 30, "6.100"
customPropMgr.Add2 "D20", 30, "11.700"
customPropMgr.Add2 "XF31", 30, "7.000"
customPropMgr.Add2 "B31", 30, "10.000"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "536393 ADN-10-P-A_(KS)"
customPropMgr.Add2 "BOMINFO", 30, "536393 ADN-10-P-A_(KS)"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
customPropMgr.Add2 "IsFastener", 30, "0"
part.SummaryInfo(0)="536393 ADN-10-P-A_(KS)"
part.SummaryInfo(4)="Compact cylinder - piston rod"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75
valRGB(1)=0.75
valRGB(2)=0.75
valRGB(7)=0
part.MaterialPropertyValues=valRGB
Dim featMgr as object
set featMgr = part.FeatureManager
codeBag38 part,featMgr
part.ActiveView.EnableGraphicsUpdate = true
part.SketchManager.DisplayWhenAdded = true
part.SketchManager.AddToDB = false
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "536393 ADN-10-P-A_(KS).sldprt",0,0,nothing,errors,warnings
End Sub
Sub CreatePart2
dim errors as long
dim warnings as long
Dim longstatus As Long
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
set res=swApp.OpenDoc6 ( storePath & "DIN-439-B - M20x1_5(F).sldprt",1,3,"", errors, warnings)
swApp.ActivateDoc2 "DIN-439-B - M20x1_5(F).sldprt", False, longstatus
if not res is nothing then
 if (docVisible=0) then
  swApp.DocumentVisible 1, 1
 end if
 exit sub
end if
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
Dim sPartTemplateName As String
sPartTemplateName = swApp.GetUserPreferenceStringValue(8)
Set part = swApp.NewDocument(sPartTemplateName, 0, 0, 0)
swApp.ActivateDoc2 "DIN-439-B - M20x1_5(F).sldprt", False, longstatus
Set part = swApp.ActiveDoc
part.SketchManager.AddToDB = true
part.SketchManager.DisplayWhenAdded = false
part.ActiveView.EnableGraphicsUpdate = false
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NB", 30, "DIN-439-B - M20x1.5(F)"
customPropMgr.Add2 "NN", 30, "DIN-439 Form B"
customPropMgr.Add2 "NT", 30, "Hex nut"
customPropMgr.Add2 "NBSYN", 30, "DIN-439-B - $NENN.(F)"
customPropMgr.Add2 "LINA", 30, "DIN-439-B - M20x1.5"
customPropMgr.Add2 "CATALOG", 30, "Festo"
customPropMgr.Add2 "ROWDESC", 30, "M20x1.5"
customPropMgr.Add2 "NENN", 30, "M20x1.5"
customPropMgr.Add2 "DG", 30, "20.000"
customPropMgr.Add2 "DK", 30, "18.376"
customPropMgr.Add2 "M", 30, "10.000"
customPropMgr.Add2 "S", 30, "30.000"
customPropMgr.Add2 "P", 30, "1.500"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "DIN-439-B - M20x1.5(F)"
customPropMgr.Add2 "BOMINFO", 30, "DIN-439-B - M20x1.5"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
customPropMgr.Add2 "IsFastener", 30, "0"
part.SummaryInfo(0)="DIN-439-B - M20x1.5"
part.SummaryInfo(4)="Hex nut"
part.SummaryInfo(2)="Cadenas PARTsolutions"
valRGB=part.MaterialPropertyValues
valRGB(0)=0.75294119119644
valRGB(1)=0.75294119119644
valRGB(2)=0.75294119119644
valRGB(7)=0
part.MaterialPropertyValues=valRGB
Dim featMgr as object
set featMgr = part.FeatureManager
codeBag43 part,featMgr
part.ActiveView.EnableGraphicsUpdate = true
part.SketchManager.DisplayWhenAdded = true
part.SketchManager.AddToDB = false
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "DIN-439-B - M20x1_5(F).sldprt",0,0,nothing,errors,warnings
End Sub
sub CreatePart3
dim errors as long
dim warnings as long
set res=swApp.OpenDoc6 ( storePath & "536393 ADN-125-10-A-P-A---(0).sldasm",2,3,"", errors, warnings)
if not res is nothing then
 exit sub
end if
codeBag47 
set part=swApp.NewAssembly
Set modelExt = part.Extension
Set customPropMgr = modelExt.CustomPropertyManager("")
customPropMgr.Add2 "NB", 30, "536393 ADN-125-10-A-P-A---(0)"
customPropMgr.Add2 "NN", 30, "ADN (mp)"
customPropMgr.Add2 "NT", 30, "Compact cylinder, Modular system"
customPropMgr.Add2 "NBSYN", 30, "$TNR. $TYP.-$HUB.-$TH.-$DF.-$GA.$QN.$S2S20N.$K2N.$K5N.$K8N.$K10N.$S6N.$S10N.$S11N.$R3N.$S1N.$TLN.$TTN.$R8N.$BWET.$EX4N.$TXTN.---($HUBST.)"
customPropMgr.Add2 "LINA", 30, "536393 ADN-125-10-A-P-A---(0)"
customPropMgr.Add2 "CATALOG", 30, "Festo"
customPropMgr.Add2 "OFFICIAL_STANDARD_NUMBERS", 30, "ISO 21287"
customPropMgr.Add2 "TNR", 30, "536393"
customPropMgr.Add2 "TYP", 30, "ADN-125"
customPropMgr.Add2 "KDM", 30, "125"
customPropMgr.Add2 "HUB", 30, "10"
customPropMgr.Add2 "TH", 30, "A"
customPropMgr.Add2 "HUBST", 30, "0"
customPropMgr.Add2 "DF", 30, "P"
customPropMgr.Add2 "GA", 30, "A"
customPropMgr.Add2 "Q", 30, "-"
customPropMgr.Add2 "S2S20", 30, "-"
customPropMgr.Add2 "K2", 30, "0"
customPropMgr.Add2 "K5", 30, "-"
customPropMgr.Add2 "K8", 30, "0"
customPropMgr.Add2 "K10", 30, "-"
customPropMgr.Add2 "S6", 30, "-"
customPropMgr.Add2 "S10", 30, "-"
customPropMgr.Add2 "S11", 30, "-"
customPropMgr.Add2 "R3", 30, "-"
customPropMgr.Add2 "S1", 30, "-"
customPropMgr.Add2 "TL", 30, "-"
customPropMgr.Add2 "TT", 30, "-"
customPropMgr.Add2 "R8", 30, "-"
customPropMgr.Add2 "BWE", 30, "-"
customPropMgr.Add2 "ATEX", 30, "-"
customPropMgr.Add2 "TXT", 30, "-"
customPropMgr.Add2 "A", 30, "40.000"
customPropMgr.Add2 "A1", 30, "0.000"
customPropMgr.Add2 "AF", 30, "25.000"
customPropMgr.Add2 "AF1", 30, "0.000"
customPropMgr.Add2 "AF2", 30, "12.000"
customPropMgr.Add2 "AF3", 30, "24.000"
customPropMgr.Add2 "AF5", 30, "0.000"
customPropMgr.Add2 "AF7", 30, "0.000"
customPropMgr.Add2 "B", 30, "0.000"
customPropMgr.Add2 "B1", 30, "0.000"
customPropMgr.Add2 "BG", 30, "20.000"
customPropMgr.Add2 "BG1", 30, "0.000"
customPropMgr.Add2 "DA", 30, "0.000"
customPropMgr.Add2 "D1", 30, "12.000"
customPropMgr.Add2 "D2", 30, "0.000"
customPropMgr.Add2 "D3", 30, "0.000"
customPropMgr.Add2 "D4", 30, "-"
customPropMgr.Add2 "D5", 30, "0.000"
customPropMgr.Add2 "D20", 30, "11.700"
customPropMgr.Add2 "D21", 30, "0.000"
customPropMgr.Add2 "E", 30, "134.600"
customPropMgr.Add2 "EE", 30, "G1/4"
customPropMgr.Add2 "EE1", 30, "-"
customPropMgr.Add2 "FB", 30, "0.000"
customPropMgr.Add2 "G", 30, "20.000"
customPropMgr.Add2 "J", 30, "20.000"
customPropMgr.Add2 "KF", 30, "M16"
customPropMgr.Add2 "KF1", 30, "-"
customPropMgr.Add2 "KF2", 30, "G1/4"
customPropMgr.Add2 "KF3", 30, "M12"
customPropMgr.Add2 "KF5", 30, "-"
customPropMgr.Add2 "KF7", 30, "-"
customPropMgr.Add2 "KK", 30, "M20x1.5"
customPropMgr.Add2 "KK1", 30, "-"
customPropMgr.Add2 "LA", 30, "0.000"
customPropMgr.Add2 "LA1", 30, "0.000"
customPropMgr.Add2 "MM", 30, "25.000"
customPropMgr.Add2 "MM1", 30, "0.000"
customPropMgr.Add2 "PL", 30, "10.500"
customPropMgr.Add2 "RR", 30, "10.100"
customPropMgr.Add2 "RT", 30, "M12"
customPropMgr.Add2 "SF", 30, "21.000"
customPropMgr.Add2 "SF1", 30, "0.000"
customPropMgr.Add2 "SF3", 30, "20.000"
customPropMgr.Add2 "TG", 30, "110.000"
customPropMgr.Add2 "U1", 30, "21.150"
customPropMgr.Add2 "U2", 30, "0.000"
customPropMgr.Add2 "VD", 30, "0.000"
customPropMgr.Add2 "VD1", 30, "0.000"
customPropMgr.Add2 "WH", 30, "11.000"
customPropMgr.Add2 "WH0", 30, "11.000"
customPropMgr.Add2 "WH1", 30, "0.000"
customPropMgr.Add2 "WH2", 30, "0.000"
customPropMgr.Add2 "WH3", 30, "0.000"
customPropMgr.Add2 "WL", 30, "9.000"
customPropMgr.Add2 "WL1", 30, "0.000"
customPropMgr.Add2 "W1", 30, "2.600"
customPropMgr.Add2 "W2", 30, "0.000"
customPropMgr.Add2 "W3", 30, "0.000"
customPropMgr.Add2 "W4", 30, "0.000"
customPropMgr.Add2 "W20", 30, "7.000"
customPropMgr.Add2 "W21", 30, "0.000"
customPropMgr.Add2 "W22", 30, "0.000"
customPropMgr.Add2 "W23", 30, "6.100"
customPropMgr.Add2 "W25", 30, "0.000"
customPropMgr.Add2 "W27", 30, "0.000"
customPropMgr.Add2 "Y1", 30, "0.500"
customPropMgr.Add2 "Y2", 30, "0.000"
customPropMgr.Add2 "ZA", 30, "81.000"
customPropMgr.Add2 "ZB", 30, "92.000"
customPropMgr.Add2 "ZB1", 30, "0.000"
customPropMgr.Add2 "ZB2", 30, "0.000"
customPropMgr.Add2 "ZB6", 30, "0.000"
customPropMgr.Add2 "ZM", 30, "104.400"
customPropMgr.Add2 "ZM2", 30, "0.000"
customPropMgr.Add2 "CNSMASSEXACT", 30, "2.997"
customPropMgr.Add2 "SUPPLIER", 30, "FESTO"
customPropMgr.Add2 "ARTICLENO", 30, "536393 ADN-125-10-A-P-A---(0)"
customPropMgr.Add2 "BOMINFO", 30, "536393 ADN-125-10-A-P-A---(0)"
customPropMgr.Add2 "CREATOR", 30, "CADENAS GmbH"
part.SummaryInfo(0)="536393 ADN-125-10-A-P-A---(0)"
part.SummaryInfo(4)="Compact cylinder, Modular system"
part.SummaryInfo(2)="Cadenas PARTsolutions"
if (docVisible=0) then
 swApp.DocumentVisible 0, 1
end if
codeBag48 part
codeBag49 
if (docVisible=0) then
 swApp.DocumentVisible 1, 1
end if
part.EditRebuild3
part.Rebuild swRebuildAll
Set modelExt = part.Extension
modelExt.SaveAs storePath & "536393 ADN-125-10-A-P-A---(0).sldasm",0,0,nothing,errors,warnings
end sub
sub codeBag1(part,wMat)
cArc part,wMat,-0.0673,0.0283,-0.067182842712475,0.028017157287525,-0.0669,0.0279
cLn part,wMat,-0.0669,0.0279,-0.0627,0.0279
cArc part,wMat,-0.0627,0.0279,-0.062417157287525,0.027782842712475,-0.0623,0.0275
cLn part,wMat,-0.0623,0.0275,-0.0623,0.0211
cArc part,wMat,-0.0623,0.0211,-0.062417157287525,0.020817157287525,-0.0627,0.0207
cLn part,wMat,-0.0627,0.0207,-0.0669,0.0207
cArc part,wMat,-0.0669,0.0207,-0.067182842712475,0.020582842712475,-0.0673,0.0203
cLn part,wMat,-0.0673,0.0203,-0.0673,-0.0203
cArc part,wMat,-0.0673,-0.0203,-0.067182842712475,-0.020582842712475,-0.0669,-0.0207
cLn part,wMat,-0.0669,-0.0207,-0.0627,-0.0207
cArc part,wMat,-0.0627,-0.0207,-0.062417157287525,-0.020817157287525,-0.0623,-0.0211
cLn part,wMat,-0.0623,-0.0211,-0.0623,-0.0275
cArc part,wMat,-0.0623,-0.0275,-0.062417157287525,-0.027782842712475,-0.0627,-0.0279
cLn part,wMat,-0.0627,-0.0279,-0.0669,-0.0279
cArc part,wMat,-0.0669,-0.0279,-0.067182842712475,-0.028017157287525,-0.0673,-0.0283
cLn part,wMat,-0.0673,-0.0283,-0.0673,-0.062300902512373
cArc part,wMat,-0.0673,-0.062300902512373,-0.067001263374422,-0.063338124411627,-0.066196585713315,-0.064057544943265
cArc part,wMat,-0.066196585713315,-0.064057544943265,-0.059281080787888,-0.066479081896445,-0.052,-0.0673
cLn part,wMat,-0.052,-0.0673,-0.0283,-0.0673
cArc part,wMat,-0.0283,-0.0673,-0.028017157287525,-0.067182842712475,-0.0279,-0.0669
cLn part,wMat,-0.0279,-0.0669,-0.0279,-0.0627
cArc part,wMat,-0.0279,-0.0627,-0.027782842712475,-0.062417157287525,-0.0275,-0.0623
cLn part,wMat,-0.0275,-0.0623,-0.0211,-0.0623
cArc part,wMat,-0.0211,-0.0623,-0.020817157287525,-0.062417157287525,-0.0207,-0.0627
cLn part,wMat,-0.0207,-0.0627,-0.0207,-0.0669
cArc part,wMat,-0.0207,-0.0669,-0.020582842712475,-0.067182842712475,-0.0203,-0.0673
cLn part,wMat,-0.0203,-0.0673,0.0203,-0.0673
cArc part,wMat,0.0203,-0.0673,0.020582842712475,-0.067182842712475,0.0207,-0.0669
cLn part,wMat,0.0207,-0.0669,0.0207,-0.0627
cArc part,wMat,0.0207,-0.0627,0.020817157287525,-0.062417157287525,0.0211,-0.0623
cLn part,wMat,0.0211,-0.0623,0.0275,-0.0623
cArc part,wMat,0.0275,-0.0623,0.027782842712475,-0.062417157287525,0.0279,-0.0627
cLn part,wMat,0.0279,-0.0627,0.0279,-0.0669
cArc part,wMat,0.0279,-0.0669,0.028017157287525,-0.067182842712475,0.0283,-0.0673
cLn part,wMat,0.0283,-0.0673,0.052,-0.0673
cArc part,wMat,0.052,-0.0673,0.059281080787888,-0.066479081896445,0.066196585365854,-0.064057545110719
cArc part,wMat,0.066196585365854,-0.064057545110719,0.067001263374422,-0.063338124411627,0.0673,-0.062300902512373
cLn part,wMat,0.0673,-0.062300902512373,0.0673,0.062300902512373
cArc part,wMat,0.0673,0.062300902512373,0.067001263374422,0.063338124411627,0.066196585565861,0.064057545014329
cArc part,wMat,0.066196585565861,0.064057545014329,0.059281080787888,0.066479081896445,0.052,0.0673
cLn part,wMat,0.052,0.0673,0.0283,0.0673
cArc part,wMat,0.0283,0.0673,0.028017157287525,0.067182842712475,0.0279,0.0669
cLn part,wMat,0.0279,0.0669,0.0279,0.0627
cArc part,wMat,0.0279,0.0627,0.027782842712475,0.062417157287525,0.0275,0.0623
cLn part,wMat,0.0275,0.0623,0.0211,0.0623
cArc part,wMat,0.0211,0.0623,0.020817157287525,0.062417157287525,0.0207,0.0627
cLn part,wMat,0.0207,0.0627,0.0207,0.0669
cArc part,wMat,0.0207,0.0669,0.020582842712475,0.067182842712475,0.0203,0.0673
cLn part,wMat,0.0203,0.0673,-0.0203,0.0673
cArc part,wMat,-0.0203,0.0673,-0.020582842712475,0.067182842712475,-0.0207,0.0669
cLn part,wMat,-0.0207,0.0669,-0.0207,0.0627
cArc part,wMat,-0.0207,0.0627,-0.020817157287525,0.062417157287525,-0.0211,0.0623
cLn part,wMat,-0.0211,0.0623,-0.0275,0.0623
cArc part,wMat,-0.0275,0.0623,-0.027782842712475,0.062417157287525,-0.0279,0.0627
cLn part,wMat,-0.0279,0.0627,-0.0279,0.0669
cArc part,wMat,-0.0279,0.0669,-0.028017157287525,0.067182842712475,-0.0283,0.0673
cLn part,wMat,-0.0283,0.0673,-0.052,0.0673
cArc part,wMat,-0.052,0.0673,-0.059281080787888,0.066479081896445,-0.066196585365854,0.064057545110719
cArc part,wMat,-0.066196585365854,0.064057545110719,-0.067001263374422,0.063338124411627,-0.0673,0.062300902512373
cLn part,wMat,-0.0673,0.062300902512373,-0.0673,0.0283
Part.SketchManager.InsertSketch True
end sub

sub codeBag2(part,wMat)
cLn part,wMat,-0.067,0.067,-0.067,-0.067
cLn part,wMat,-0.067,-0.067,0.067,-0.067
cLn part,wMat,0.067,-0.067,0.067,0.067
cLn part,wMat,0.067,0.067,-0.067,0.067
Part.SketchManager.InsertSketch True
end sub

sub codeBag3(part,wMat)
cLn part,wMat,-0.1,0.1,-0.1,-0.1
cLn part,wMat,-0.1,-0.1,0.1,-0.1
cLn part,wMat,0.1,-0.1,0.1,0.1
cLn part,wMat,0.1,0.1,-0.1,0.1
cArc part,wMat,-0.067,0.0273,-0.066882842712475,0.027017157287525,-0.0666,0.0269
cLn part,wMat,-0.0666,0.0269,-0.0659,0.0269
cArc part,wMat,-0.0659,0.0269,-0.065758578643763,0.026958578643763,-0.0657,0.0271
cLn part,wMat,-0.0657,0.0271,-0.0657,0.02735
cArc part,wMat,-0.0657,0.02735,-0.065641421356237,0.027491421356237,-0.0655,0.02755
cLn part,wMat,-0.0655,0.02755,-0.0629,0.02755
cArc part,wMat,-0.0629,0.02755,-0.062617157287525,0.027432842712475,-0.0625,0.02715
cLn part,wMat,-0.0625,0.02715,-0.0625,0.02145
cArc part,wMat,-0.0625,0.02145,-0.062617157287525,0.021167157287525,-0.0629,0.02105
cLn part,wMat,-0.0629,0.02105,-0.0655,0.02105
cArc part,wMat,-0.0655,0.02105,-0.065641421356237,0.021108578643763,-0.0657,0.02125
cLn part,wMat,-0.0657,0.02125,-0.0657,0.0215
cArc part,wMat,-0.0657,0.0215,-0.065758578643763,0.021641421356237,-0.0659,0.0217
cLn part,wMat,-0.0659,0.0217,-0.0666,0.0217
cArc part,wMat,-0.0666,0.0217,-0.066882842712475,0.021582842712475,-0.067,0.0213
cLn part,wMat,-0.067,0.0213,-0.067,-0.0213
cArc part,wMat,-0.067,-0.0213,-0.066882842712475,-0.021582842712475,-0.0666,-0.0217
cLn part,wMat,-0.0666,-0.0217,-0.0659,-0.0217
cArc part,wMat,-0.0659,-0.0217,-0.065758578643763,-0.021641421356237,-0.0657,-0.0215
cLn part,wMat,-0.0657,-0.0215,-0.0657,-0.02125
cArc part,wMat,-0.0657,-0.02125,-0.065641421356237,-0.021108578643763,-0.0655,-0.02105
cLn part,wMat,-0.0655,-0.02105,-0.0629,-0.02105
cArc part,wMat,-0.0629,-0.02105,-0.062617157287525,-0.021167157287525,-0.0625,-0.02145
cLn part,wMat,-0.0625,-0.02145,-0.0625,-0.02715
cArc part,wMat,-0.0625,-0.02715,-0.062617157287525,-0.027432842712475,-0.0629,-0.02755
cLn part,wMat,-0.0629,-0.02755,-0.0655,-0.02755
cArc part,wMat,-0.0655,-0.02755,-0.065641421356237,-0.027491421356237,-0.0657,-0.02735
cLn part,wMat,-0.0657,-0.02735,-0.0657,-0.0271
cArc part,wMat,-0.0657,-0.0271,-0.065758578643763,-0.026958578643763,-0.0659,-0.0269
cLn part,wMat,-0.0659,-0.0269,-0.0666,-0.0269
cArc part,wMat,-0.0666,-0.0269,-0.066882842712475,-0.027017157287525,-0.067,-0.0273
cLn part,wMat,-0.067,-0.0273,-0.067,-0.062269477768834
cArc part,wMat,-0.067,-0.062269477768834,-0.066739100334232,-0.063174458557588,-0.066036482279313,-0.063801663740659
cArc part,wMat,-0.066036482279313,-0.063801663740659,-0.05919812794314,-0.066190298417618,-0.052,-0.067
cLn part,wMat,-0.052,-0.067,-0.0273,-0.067
cArc part,wMat,-0.0273,-0.067,-0.027017157287525,-0.066882842712475,-0.0269,-0.0666
cLn part,wMat,-0.0269,-0.0666,-0.0269,-0.0659
cArc part,wMat,-0.0269,-0.0659,-0.026958578643763,-0.065758578643763,-0.0271,-0.0657
cLn part,wMat,-0.0271,-0.0657,-0.02735,-0.0657
cArc part,wMat,-0.02735,-0.0657,-0.027491421356237,-0.065641421356237,-0.02755,-0.0655
cLn part,wMat,-0.02755,-0.0655,-0.02755,-0.0629
cArc part,wMat,-0.02755,-0.0629,-0.027432842712475,-0.062617157287525,-0.02715,-0.0625
cLn part,wMat,-0.02715,-0.0625,-0.02145,-0.0625
cArc part,wMat,-0.02145,-0.0625,-0.021167157287525,-0.062617157287525,-0.02105,-0.0629
cLn part,wMat,-0.02105,-0.0629,-0.02105,-0.0655
cArc part,wMat,-0.02105,-0.0655,-0.021108578643763,-0.065641421356237,-0.02125,-0.0657
cLn part,wMat,-0.02125,-0.0657,-0.0215,-0.0657
cArc part,wMat,-0.0215,-0.0657,-0.021641421356237,-0.065758578643763,-0.0217,-0.0659
cLn part,wMat,-0.0217,-0.0659,-0.0217,-0.0666
cArc part,wMat,-0.0217,-0.0666,-0.021582842712475,-0.066882842712475,-0.0213,-0.067
cLn part,wMat,-0.0213,-0.067,0.0213,-0.067
cArc part,wMat,0.0213,-0.067,0.021582842712475,-0.066882842712475,0.0217,-0.0666
cLn part,wMat,0.0217,-0.0666,0.0217,-0.0659
cArc part,wMat,0.0217,-0.0659,0.021641421356237,-0.065758578643763,0.0215,-0.0657
cLn part,wMat,0.0215,-0.0657,0.02125,-0.0657
cArc part,wMat,0.02125,-0.0657,0.021108578643763,-0.065641421356237,0.02105,-0.0655
cLn part,wMat,0.02105,-0.0655,0.02105,-0.0629
cArc part,wMat,0.02105,-0.0629,0.021167157287525,-0.062617157287525,0.02145,-0.0625
cLn part,wMat,0.02145,-0.0625,0.02715,-0.0625
cArc part,wMat,0.02715,-0.0625,0.027432842712475,-0.062617157287525,0.02755,-0.0629
cLn part,wMat,0.02755,-0.0629,0.02755,-0.0655
cArc part,wMat,0.02755,-0.0655,0.027491421356237,-0.065641421356237,0.02735,-0.0657
cLn part,wMat,0.02735,-0.0657,0.0271,-0.0657
cArc part,wMat,0.0271,-0.0657,0.026958578643763,-0.065758578643763,0.0269,-0.0659
cLn part,wMat,0.0269,-0.0659,0.0269,-0.0666
cArc part,wMat,0.0269,-0.0666,0.027017157287525,-0.066882842712475,0.0273,-0.067
cLn part,wMat,0.0273,-0.067,0.052,-0.067
cArc part,wMat,0.052,-0.067,0.05919812794314,-0.066190298417618,0.066036482084691,-0.063801663834209
cArc part,wMat,0.066036482084691,-0.063801663834209,0.066739100334232,-0.063174458557588,0.067,-0.062269477768834
cLn part,wMat,0.067,-0.062269477768834,0.067,0.062269477768834
cArc part,wMat,0.067,0.062269477768834,0.066739100334232,0.063174458557588,0.066036482279313,0.063801663740659
cArc part,wMat,0.066036482279313,0.063801663740659,0.05919812794314,0.066190298417618,0.052,0.067
cLn part,wMat,0.052,0.067,0.0273,0.067
cArc part,wMat,0.0273,0.067,0.027017157287525,0.066882842712475,0.0269,0.0666
cLn part,wMat,0.0269,0.0666,0.0269,0.0659
cArc part,wMat,0.0269,0.0659,0.026958578643763,0.065758578643763,0.0271,0.0657
cLn part,wMat,0.0271,0.0657,0.02735,0.0657
cArc part,wMat,0.02735,0.0657,0.027491421356237,0.065641421356237,0.02755,0.0655
cLn part,wMat,0.02755,0.0655,0.02755,0.0629
cArc part,wMat,0.02755,0.0629,0.027432842712475,0.062617157287525,0.02715,0.0625
cLn part,wMat,0.02715,0.0625,0.02145,0.0625
cArc part,wMat,0.02145,0.0625,0.021167157287525,0.062617157287525,0.02105,0.0629
cLn part,wMat,0.02105,0.0629,0.02105,0.0655
cArc part,wMat,0.02105,0.0655,0.021108578643763,0.065641421356237,0.02125,0.0657
cLn part,wMat,0.02125,0.0657,0.0215,0.0657
cArc part,wMat,0.0215,0.0657,0.021641421356237,0.065758578643763,0.0217,0.0659
cLn part,wMat,0.0217,0.0659,0.0217,0.0666
cArc part,wMat,0.0217,0.0666,0.021582842712475,0.066882842712475,0.0213,0.067
cLn part,wMat,0.0213,0.067,-0.0213,0.067
cArc part,wMat,-0.0213,0.067,-0.021582842712475,0.066882842712475,-0.0217,0.0666
cLn part,wMat,-0.0217,0.0666,-0.0217,0.0659
cArc part,wMat,-0.0217,0.0659,-0.021641421356237,0.065758578643763,-0.0215,0.0657
cLn part,wMat,-0.0215,0.0657,-0.02125,0.0657
cArc part,wMat,-0.02125,0.0657,-0.021108578643763,0.065641421356237,-0.02105,0.0655
cLn part,wMat,-0.02105,0.0655,-0.02105,0.0629
cArc part,wMat,-0.02105,0.0629,-0.021167157287525,0.062617157287525,-0.02145,0.0625
cLn part,wMat,-0.02145,0.0625,-0.02715,0.0625
cArc part,wMat,-0.02715,0.0625,-0.027432842712475,0.062617157287525,-0.02755,0.0629
cLn part,wMat,-0.02755,0.0629,-0.02755,0.0655
cArc part,wMat,-0.02755,0.0655,-0.027491421356237,0.065641421356237,-0.02735,0.0657
cLn part,wMat,-0.02735,0.0657,-0.0271,0.0657
cArc part,wMat,-0.0271,0.0657,-0.026958578643763,0.065758578643763,-0.0269,0.0659
cLn part,wMat,-0.0269,0.0659,-0.0269,0.0666
cArc part,wMat,-0.0269,0.0666,-0.027017157287525,0.066882842712475,-0.0273,0.067
cLn part,wMat,-0.0273,0.067,-0.052,0.067
cArc part,wMat,-0.052,0.067,-0.05919812794314,0.066190298417618,-0.066036482084691,0.063801663834209
cArc part,wMat,-0.066036482084691,0.063801663834209,-0.066739100334232,0.063174458557588,-0.067,0.062269477768834
cLn part,wMat,-0.067,0.062269477768834,-0.067,0.0273
Part.SketchManager.InsertSketch True
end sub

sub codeBag4(part,wMat)
cLn part,wMat,0.0395,0.0105,0.0395,0.0162225
cLn part,wMat,0.0395,0.0162225,0.066444,0.0162225
cLn part,wMat,0.066444,0.0162225,0.0673,0.0170785
cLn part,wMat,0.0673,0.0170785,0.0673,0.0105
cLn part,wMat,0.0673,0.0105,0.0395,0.0105
cCLn part,wMat,0.0673,0.0105,0.0395,0.0105
Part.SketchManager.InsertSketch True
end sub

sub codeBag5(part,wMat)
cLn part,wMat,0.0395,0.0805,0.0395,0.0862225
cLn part,wMat,0.0395,0.0862225,0.066444,0.0862225
cLn part,wMat,0.066444,0.0862225,0.0673,0.0870785
cLn part,wMat,0.0673,0.0870785,0.0673,0.0805
cLn part,wMat,0.0673,0.0805,0.0395,0.0805
cCLn part,wMat,0.0673,0.0805,0.0395,0.0805
Part.SketchManager.InsertSketch True
end sub

sub codeBag6(part,wMat)
cLn part,wMat,-0.001,0,-0.001,0.0125
cLn part,wMat,-0.001,0.0125,0.02875,0.0125
cLn part,wMat,0.02875,0.0125,0.02875,0.0625
cLn part,wMat,0.02875,0.0625,0.07,0.0625
cLn part,wMat,0.07,0.0625,0.07,0
cLn part,wMat,0.07,0,-0.001,0
cCLn part,wMat,0.07,0,-0.001,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag7(part,wMat)
cLn part,wMat,0.0884,0,0.0884,0.006
cLn part,wMat,0.0884,0.006,0.091,0.006
cLn part,wMat,0.091,0.006,0.091,0
cLn part,wMat,0.091,0,0.0884,0
cCLn part,wMat,0.091,0,0.0884,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag8(part,wMat)
cLn part,wMat,0.039,0.0058038475772934,0.042,0.005
cLn part,wMat,0.042,0.005,0.042,0.00148
cLn part,wMat,0.042,0.00148,0.04248,0.001
cLn part,wMat,0.04248,0.001,0.0447,0.001
cLn part,wMat,0.0447,0.001,0.0455,0.0018
cLn part,wMat,0.0455,0.0018,0.0455,0.009
cLn part,wMat,0.0455,0.009,0.04625,0.009
cLn part,wMat,0.04625,0.009,0.04625,-0.001
cLn part,wMat,0.04625,-0.001,0.039,-0.001
cLn part,wMat,0.039,-0.001,0.039,0.0058038475772934
cCLn part,wMat,0.039,-0.001,0.039,0.0058038475772934
Part.SketchManager.InsertSketch True
end sub

sub codeBag9(part,wMat)
cLn part,wMat,-0.039,0.0058038475772934,-0.036,0.005
cLn part,wMat,-0.036,0.005,-0.036,0.00148
cLn part,wMat,-0.036,0.00148,-0.03552,0.001
cLn part,wMat,-0.03552,0.001,-0.0333,0.001
cLn part,wMat,-0.0333,0.001,-0.0325,0.0018
cLn part,wMat,-0.0325,0.0018,-0.0325,0.009
cLn part,wMat,-0.0325,0.009,-0.03175,0.009
cLn part,wMat,-0.03175,0.009,-0.03175,-0.001
cLn part,wMat,-0.03175,-0.001,-0.039,-0.001
cLn part,wMat,-0.039,-0.001,-0.039,0.0058038475772934
cCLn part,wMat,-0.039,-0.001,-0.039,0.0058038475772934
Part.SketchManager.InsertSketch True
end sub

sub codeBag10(part,wMat)
cLn part,wMat,0.039,0.0058038475772934,0.042,0.005
cLn part,wMat,0.042,0.005,0.042,0.00148
cLn part,wMat,0.042,0.00148,0.04248,0.001
cLn part,wMat,0.04248,0.001,0.0447,0.001
cLn part,wMat,0.0447,0.001,0.0455,0.0018
cLn part,wMat,0.0455,0.0018,0.0455,0.009
cLn part,wMat,0.0455,0.009,0.04625,0.009
cLn part,wMat,0.04625,0.009,0.04625,-0.001
cLn part,wMat,0.04625,-0.001,0.039,-0.001
cLn part,wMat,0.039,-0.001,0.039,0.0058038475772934
cCLn part,wMat,0.039,-0.001,0.039,0.0058038475772934
Part.SketchManager.InsertSketch True
end sub

sub codeBag11(part,wMat)
cLn part,wMat,-0.039,0.0058038475772934,-0.036,0.005
cLn part,wMat,-0.036,0.005,-0.036,0.00148
cLn part,wMat,-0.036,0.00148,-0.03552,0.001
cLn part,wMat,-0.03552,0.001,-0.0333,0.001
cLn part,wMat,-0.0333,0.001,-0.0325,0.0018
cLn part,wMat,-0.0325,0.0018,-0.0325,0.009
cLn part,wMat,-0.0325,0.009,-0.03175,0.009
cLn part,wMat,-0.03175,0.009,-0.03175,-0.001
cLn part,wMat,-0.03175,-0.001,-0.039,-0.001
cLn part,wMat,-0.039,-0.001,-0.039,0.0058038475772934
cCLn part,wMat,-0.039,-0.001,-0.039,0.0058038475772934
Part.SketchManager.InsertSketch True
end sub

sub codeBag12(part,wMat)
cLn part,wMat,0.039,0.092,0.04625,0.092
cLn part,wMat,0.04625,0.092,0.04625,0.082
cLn part,wMat,0.04625,0.082,0.0455,0.082
cLn part,wMat,0.0455,0.082,0.0455,0.0892
cLn part,wMat,0.0455,0.0892,0.0447,0.09
cLn part,wMat,0.0447,0.09,0.04248,0.09
cLn part,wMat,0.04248,0.09,0.042,0.08952
cLn part,wMat,0.042,0.08952,0.042,0.086
cLn part,wMat,0.042,0.086,0.039,0.085196152422707
cLn part,wMat,0.039,0.085196152422707,0.039,0.092
cCLn part,wMat,0.039,0.085196152422707,0.039,0.092
Part.SketchManager.InsertSketch True
end sub

sub codeBag13(part,wMat)
cLn part,wMat,-0.039,0.092,-0.03175,0.092
cLn part,wMat,-0.03175,0.092,-0.03175,0.082
cLn part,wMat,-0.03175,0.082,-0.0325,0.082
cLn part,wMat,-0.0325,0.082,-0.0325,0.0892
cLn part,wMat,-0.0325,0.0892,-0.0333,0.09
cLn part,wMat,-0.0333,0.09,-0.03552,0.09
cLn part,wMat,-0.03552,0.09,-0.036,0.08952
cLn part,wMat,-0.036,0.08952,-0.036,0.086
cLn part,wMat,-0.036,0.086,-0.039,0.085196152422707
cLn part,wMat,-0.039,0.085196152422707,-0.039,0.092
cCLn part,wMat,-0.039,0.085196152422707,-0.039,0.092
Part.SketchManager.InsertSketch True
end sub

sub codeBag0(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag1 part,wMat
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
featMgr.FeatureExtrusion2 1,0,1,0,0,0.091,0.091,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.02),createVec3d(1,0,-0.02),createVec3d(0,1,-0.02),1
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.02)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag2 part,wMat
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
featMgr.FeatureExtrusion2 1,0,1,0,0,0.051,0.051,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.02),createVec3d(1,0,-0.02),createVec3d(0,1,-0.02),1
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.02)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag3 part,wMat
set feat10=part.Extension.GetLastFeatureAdded()
feat10.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.051,0.051,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,-0.02115,0),createVec3d(1,-0.02115,0),createVec3d(0,-0.02115,-1),1
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,-0.02115,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag4 part,wMat
set feat16=part.Extension.GetLastFeatureAdded()
feat16.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.066444,-0.0154275,-0.0105),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.013157,0.013,""
 elseif getEdgeFromModel(part,createVec3d(0.0543,-0.0154275,-0.0105),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.013157,0.013,""
 End If
part.CreatePlaneFixed2 createVec3d(0,0.02115,0),createVec3d(1,0.02115,0),createVec3d(0,0.02115,-1),1
set feat18=part.Extension.GetLastFeatureAdded()
feat18.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.02115,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag5 part,wMat
set feat18=part.Extension.GetLastFeatureAdded()
feat18.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.066444,0.0268725,-0.0805),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.013157,0.013,""
 elseif getEdgeFromModel(part,createVec3d(0.0543,0.0268725,-0.0805),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.013157,0.013,""
 End If
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag6 part,wMat
set feat20=part.Extension.GetLastFeatureAdded()
feat20.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(0,0,-1),createVec3d(0,1,0),1
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag7 part,wMat
set feat22=part.Extension.GetLastFeatureAdded()
feat22.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0.0585,0),createVec3d(1,0.0585,0),createVec3d(0,0.0585,-1),1
set feat28=part.Extension.GetLastFeatureAdded()
feat28.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag8 part,wMat
set feat28=part.Extension.GetLastFeatureAdded()
feat28.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0.0585,0),createVec3d(1,0.0585,0),createVec3d(0,0.0585,-1),1
set feat30=part.Extension.GetLastFeatureAdded()
feat30.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag9 part,wMat
set feat30=part.Extension.GetLastFeatureAdded()
feat30.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,-0.0585,0),createVec3d(1,-0.0585,0),createVec3d(0,-0.0585,-1),1
set feat32=part.Extension.GetLastFeatureAdded()
feat32.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,-0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag10 part,wMat
set feat32=part.Extension.GetLastFeatureAdded()
feat32.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,-0.0585,0),createVec3d(1,-0.0585,0),createVec3d(0,-0.0585,-1),1
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,-0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag11 part,wMat
set feat34=part.Extension.GetLastFeatureAdded()
feat34.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0.0585,0),createVec3d(1,0.0585,0),createVec3d(0,0.0585,-1),1
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag12 part,wMat
set feat36=part.Extension.GetLastFeatureAdded()
feat36.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0.0585,0),createVec3d(1,0.0585,0),createVec3d(0,0.0585,-1),1
set feat38=part.Extension.GetLastFeatureAdded()
feat38.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag13 part,wMat
set feat38=part.Extension.GetLastFeatureAdded()
feat38.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
end sub

sub codeBag15(part,wMat)
cLn part,wMat,-0.039,0.092,-0.03175,0.092
cLn part,wMat,-0.03175,0.092,-0.03175,0.082
cLn part,wMat,-0.03175,0.082,-0.0325,0.082
cLn part,wMat,-0.0325,0.082,-0.0325,0.0892
cLn part,wMat,-0.0325,0.0892,-0.0333,0.09
cLn part,wMat,-0.0333,0.09,-0.03552,0.09
cLn part,wMat,-0.03552,0.09,-0.036,0.08952
cLn part,wMat,-0.036,0.08952,-0.036,0.086
cLn part,wMat,-0.036,0.086,-0.039,0.085196152422707
cLn part,wMat,-0.039,0.085196152422707,-0.039,0.092
cCLn part,wMat,-0.039,0.085196152422707,-0.039,0.092
Part.SketchManager.InsertSketch True
end sub

sub codeBag16(part,wMat)
cLn part,wMat,0.039,0.092,0.04625,0.092
cLn part,wMat,0.04625,0.092,0.04625,0.082
cLn part,wMat,0.04625,0.082,0.0455,0.082
cLn part,wMat,0.0455,0.082,0.0455,0.0892
cLn part,wMat,0.0455,0.0892,0.0447,0.09
cLn part,wMat,0.0447,0.09,0.04248,0.09
cLn part,wMat,0.04248,0.09,0.042,0.08952
cLn part,wMat,0.042,0.08952,0.042,0.086
cLn part,wMat,0.042,0.086,0.039,0.085196152422707
cLn part,wMat,0.039,0.085196152422707,0.039,0.092
cCLn part,wMat,0.039,0.085196152422707,0.039,0.092
Part.SketchManager.InsertSketch True
end sub

sub codeBag17(part,wMat)
cLn part,wMat,0.036,0.056767949192431,0.039,0.055035898384862
cLn part,wMat,0.039,0.055035898384862,0.042,0.056767949192431
cLn part,wMat,0.042,0.056767949192431,0.042,0.060232050807569
cLn part,wMat,0.042,0.060232050807569,0.039,0.061964101615138
cLn part,wMat,0.039,0.061964101615138,0.036,0.060232050807569
cLn part,wMat,0.036,0.060232050807569,0.036,0.056767949192431
Part.SketchManager.InsertSketch True
end sub

sub codeBag18(part,wMat)
cLn part,wMat,-0.042,0.056767949192431,-0.039,0.055035898384862
cLn part,wMat,-0.039,0.055035898384862,-0.036,0.056767949192431
cLn part,wMat,-0.036,0.056767949192431,-0.036,0.060232050807569
cLn part,wMat,-0.036,0.060232050807569,-0.039,0.061964101615138
cLn part,wMat,-0.039,0.061964101615138,-0.042,0.060232050807569
cLn part,wMat,-0.042,0.060232050807569,-0.042,0.056767949192431
Part.SketchManager.InsertSketch True
end sub

sub codeBag19(part,wMat)
cLn part,wMat,-0.042,-0.060232050807569,-0.039,-0.061964101615138
cLn part,wMat,-0.039,-0.061964101615138,-0.036,-0.060232050807569
cLn part,wMat,-0.036,-0.060232050807569,-0.036,-0.056767949192431
cLn part,wMat,-0.036,-0.056767949192431,-0.039,-0.055035898384862
cLn part,wMat,-0.039,-0.055035898384862,-0.042,-0.056767949192431
cLn part,wMat,-0.042,-0.056767949192431,-0.042,-0.060232050807569
Part.SketchManager.InsertSketch True
end sub

sub codeBag20(part,wMat)
cLn part,wMat,0.036,-0.060232050807569,0.039,-0.061964101615138
cLn part,wMat,0.039,-0.061964101615138,0.042,-0.060232050807569
cLn part,wMat,0.042,-0.060232050807569,0.042,-0.056767949192431
cLn part,wMat,0.042,-0.056767949192431,0.039,-0.055035898384862
cLn part,wMat,0.039,-0.055035898384862,0.036,-0.056767949192431
cLn part,wMat,0.036,-0.056767949192431,0.036,-0.060232050807569
Part.SketchManager.InsertSketch True
end sub

sub codeBag21(part,wMat)
cLn part,wMat,0.036,0.056767949192431,0.039,0.055035898384862
cLn part,wMat,0.039,0.055035898384862,0.042,0.056767949192431
cLn part,wMat,0.042,0.056767949192431,0.042,0.060232050807569
cLn part,wMat,0.042,0.060232050807569,0.039,0.061964101615138
cLn part,wMat,0.039,0.061964101615138,0.036,0.060232050807569
cLn part,wMat,0.036,0.060232050807569,0.036,0.056767949192431
Part.SketchManager.InsertSketch True
end sub

sub codeBag22(part,wMat)
cLn part,wMat,-0.042,0.056767949192431,-0.039,0.055035898384862
cLn part,wMat,-0.039,0.055035898384862,-0.036,0.056767949192431
cLn part,wMat,-0.036,0.056767949192431,-0.036,0.060232050807569
cLn part,wMat,-0.036,0.060232050807569,-0.039,0.061964101615138
cLn part,wMat,-0.039,0.061964101615138,-0.042,0.060232050807569
cLn part,wMat,-0.042,0.060232050807569,-0.042,0.056767949192431
Part.SketchManager.InsertSketch True
end sub

sub codeBag23(part,wMat)
cLn part,wMat,-0.042,-0.060232050807569,-0.039,-0.061964101615138
cLn part,wMat,-0.039,-0.061964101615138,-0.036,-0.060232050807569
cLn part,wMat,-0.036,-0.060232050807569,-0.036,-0.056767949192431
cLn part,wMat,-0.036,-0.056767949192431,-0.039,-0.055035898384862
cLn part,wMat,-0.039,-0.055035898384862,-0.042,-0.056767949192431
cLn part,wMat,-0.042,-0.056767949192431,-0.042,-0.060232050807569
Part.SketchManager.InsertSketch True
end sub

sub codeBag24(part,wMat)
cLn part,wMat,0.036,-0.060232050807569,0.039,-0.061964101615138
cLn part,wMat,0.039,-0.061964101615138,0.042,-0.060232050807569
cLn part,wMat,0.042,-0.060232050807569,0.042,-0.056767949192431
cLn part,wMat,0.042,-0.056767949192431,0.039,-0.055035898384862
cLn part,wMat,0.039,-0.055035898384862,0.036,-0.056767949192431
cLn part,wMat,0.036,-0.056767949192431,0.036,-0.060232050807569
Part.SketchManager.InsertSketch True
end sub

sub codeBag25(part,wMat)
cLn part,wMat,0,0.055,0,0.061
cLn part,wMat,0,0.061,0.000947,0.060053
cLn part,wMat,0.000947,0.060053,0.02,0.060053
cLn part,wMat,0.02,0.060053,0.02,0.055
cLn part,wMat,0.02,0.055,0,0.055
cCLn part,wMat,0.02,0.055,0,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag26(part,wMat)
cLn part,wMat,0,0.055,0,0.061
cLn part,wMat,0,0.061,0.000947,0.060053
cLn part,wMat,0.000947,0.060053,0.02,0.060053
cLn part,wMat,0.02,0.060053,0.02,0.055
cLn part,wMat,0.02,0.055,0,0.055
cCLn part,wMat,0.02,0.055,0,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag27(part,wMat)
cLn part,wMat,0,-0.055,0,-0.049
cLn part,wMat,0,-0.049,0.000947,-0.049947
cLn part,wMat,0.000947,-0.049947,0.02,-0.049947
cLn part,wMat,0.02,-0.049947,0.02,-0.055
cLn part,wMat,0.02,-0.055,0,-0.055
cCLn part,wMat,0.02,-0.055,0,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag14(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,-0.0585,0),createVec3d(1,-0.0585,0),createVec3d(0,-0.0585,-1),1
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,-0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag15 part,wMat
set feat40=part.Extension.GetLastFeatureAdded()
feat40.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,-0.0585,0),createVec3d(1,-0.0585,0),createVec3d(0,-0.0585,-1),1
set feat42=part.Extension.GetLastFeatureAdded()
feat42.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,-0.0585,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag16 part,wMat
set feat42=part.Extension.GetLastFeatureAdded()
feat42.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0,0,-0.001),createVec3d(1,0,-0.001),createVec3d(0,1,-0.001),1
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.001)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag17 part,wMat
set feat45=part.Extension.GetLastFeatureAdded()
feat45.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.001),createVec3d(1,0,-0.001),createVec3d(0,1,-0.001),1
set feat47=part.Extension.GetLastFeatureAdded()
feat47.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.001)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag18 part,wMat
set feat47=part.Extension.GetLastFeatureAdded()
feat47.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.001),createVec3d(1,0,-0.001),createVec3d(0,1,-0.001),1
set feat49=part.Extension.GetLastFeatureAdded()
feat49.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.001)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag19 part,wMat
set feat49=part.Extension.GetLastFeatureAdded()
feat49.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.001),createVec3d(1,0,-0.001),createVec3d(0,1,-0.001),1
set feat51=part.Extension.GetLastFeatureAdded()
feat51.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.001)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag20 part,wMat
set feat51=part.Extension.GetLastFeatureAdded()
feat51.select2 false,0
featMgr.FeatureCut3 1,0,0,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.09),createVec3d(1,0,-0.09),createVec3d(0,1,-0.09),1
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.09)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag21 part,wMat
set feat54=part.Extension.GetLastFeatureAdded()
feat54.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.09),createVec3d(1,0,-0.09),createVec3d(0,1,-0.09),1
set feat56=part.Extension.GetLastFeatureAdded()
feat56.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.09)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag22 part,wMat
set feat56=part.Extension.GetLastFeatureAdded()
feat56.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.09),createVec3d(1,0,-0.09),createVec3d(0,1,-0.09),1
set feat58=part.Extension.GetLastFeatureAdded()
feat58.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.09)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag23 part,wMat
set feat58=part.Extension.GetLastFeatureAdded()
feat58.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,-0.09),createVec3d(1,0,-0.09),createVec3d(0,1,-0.09),1
set feat60=part.Extension.GetLastFeatureAdded()
feat60.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,-0.09)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag24 part,wMat
set feat60=part.Extension.GetLastFeatureAdded()
feat60.select2 false,0
featMgr.FeatureCut3 1,0,1,0,0,0.004,0.004,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat63=part.Extension.GetLastFeatureAdded()
feat63.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag25 part,wMat
set feat63=part.Extension.GetLastFeatureAdded()
feat63.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.049947,0.055,-0.000947),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(0.049947,0.055,-0.02),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat65=part.Extension.GetLastFeatureAdded()
feat65.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag26 part,wMat
set feat65=part.Extension.GetLastFeatureAdded()
feat65.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(-0.060053,0.055,-0.000947),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(-0.060053,0.055,-0.02),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat67=part.Extension.GetLastFeatureAdded()
feat67.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag27 part,wMat
set feat67=part.Extension.GetLastFeatureAdded()
feat67.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.049947,-0.055,-0.000947),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(0.049947,-0.055,-0.02),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
end sub

sub codeBag29(part,wMat)
cLn part,wMat,0,-0.055,0,-0.049
cLn part,wMat,0,-0.049,0.000947,-0.049947
cLn part,wMat,0.000947,-0.049947,0.02,-0.049947
cLn part,wMat,0.02,-0.049947,0.02,-0.055
cLn part,wMat,0.02,-0.055,0,-0.055
cCLn part,wMat,0.02,-0.055,0,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag30(part,wMat)
cLn part,wMat,0.071,0.055,0.071,0.060053
cLn part,wMat,0.071,0.060053,0.090053,0.060053
cLn part,wMat,0.090053,0.060053,0.091,0.061
cLn part,wMat,0.091,0.061,0.091,0.055
cLn part,wMat,0.091,0.055,0.071,0.055
cCLn part,wMat,0.091,0.055,0.071,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag31(part,wMat)
cLn part,wMat,0.02,0.055,0.02,0.0605
cLn part,wMat,0.02,0.0605,0.071,0.0605
cLn part,wMat,0.071,0.0605,0.071,0.055
cLn part,wMat,0.071,0.055,0.02,0.055
cCLn part,wMat,0.071,0.055,0.02,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag32(part,wMat)
cLn part,wMat,0.071,0.055,0.071,0.060053
cLn part,wMat,0.071,0.060053,0.090053,0.060053
cLn part,wMat,0.090053,0.060053,0.091,0.061
cLn part,wMat,0.091,0.061,0.091,0.055
cLn part,wMat,0.091,0.055,0.071,0.055
cCLn part,wMat,0.091,0.055,0.071,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag33(part,wMat)
cLn part,wMat,0.02,0.055,0.02,0.0605
cLn part,wMat,0.02,0.0605,0.071,0.0605
cLn part,wMat,0.071,0.0605,0.071,0.055
cLn part,wMat,0.071,0.055,0.02,0.055
cCLn part,wMat,0.071,0.055,0.02,0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag34(part,wMat)
cLn part,wMat,0.071,-0.055,0.071,-0.049947
cLn part,wMat,0.071,-0.049947,0.090053,-0.049947
cLn part,wMat,0.090053,-0.049947,0.091,-0.049
cLn part,wMat,0.091,-0.049,0.091,-0.055
cLn part,wMat,0.091,-0.055,0.071,-0.055
cCLn part,wMat,0.091,-0.055,0.071,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag35(part,wMat)
cLn part,wMat,0.02,-0.055,0.02,-0.0495
cLn part,wMat,0.02,-0.0495,0.071,-0.0495
cLn part,wMat,0.071,-0.0495,0.071,-0.055
cLn part,wMat,0.071,-0.055,0.02,-0.055
cCLn part,wMat,0.071,-0.055,0.02,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag36(part,wMat)
cLn part,wMat,0.071,-0.055,0.071,-0.049947
cLn part,wMat,0.071,-0.049947,0.090053,-0.049947
cLn part,wMat,0.090053,-0.049947,0.091,-0.049
cLn part,wMat,0.091,-0.049,0.091,-0.055
cLn part,wMat,0.091,-0.055,0.071,-0.055
cCLn part,wMat,0.091,-0.055,0.071,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag37(part,wMat)
cLn part,wMat,0.02,-0.055,0.02,-0.0495
cLn part,wMat,0.02,-0.0495,0.071,-0.0495
cLn part,wMat,0.071,-0.0495,0.071,-0.055
cLn part,wMat,0.071,-0.055,0.02,-0.055
cCLn part,wMat,0.071,-0.055,0.02,-0.055
Part.SketchManager.InsertSketch True
end sub

sub codeBag28(part,featMgr)
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat69=part.Extension.GetLastFeatureAdded()
feat69.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag29 part,wMat
set feat69=part.Extension.GetLastFeatureAdded()
feat69.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(-0.060053,-0.055,-0.000947),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(-0.060053,-0.055,-0.02),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat71=part.Extension.GetLastFeatureAdded()
feat71.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag30 part,wMat
set feat71=part.Extension.GetLastFeatureAdded()
feat71.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.049947,0.055,-0.090053),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(0.049947,0.055,-0.071),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat73=part.Extension.GetLastFeatureAdded()
feat73.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag31 part,wMat
set feat73=part.Extension.GetLastFeatureAdded()
feat73.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat75=part.Extension.GetLastFeatureAdded()
feat75.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag32 part,wMat
set feat75=part.Extension.GetLastFeatureAdded()
feat75.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(-0.060053,0.055,-0.090053),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(-0.060053,0.055,-0.071),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat77=part.Extension.GetLastFeatureAdded()
feat77.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag33 part,wMat
set feat77=part.Extension.GetLastFeatureAdded()
feat77.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat79=part.Extension.GetLastFeatureAdded()
feat79.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag34 part,wMat
set feat79=part.Extension.GetLastFeatureAdded()
feat79.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0.049947,-0.055,-0.090053),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(0.049947,-0.055,-0.071),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(0.055,0,0),createVec3d(0.055,0,-1),createVec3d(0.055,1,0),1
set feat81=part.Extension.GetLastFeatureAdded()
feat81.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag35 part,wMat
set feat81=part.Extension.GetLastFeatureAdded()
feat81.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat83=part.Extension.GetLastFeatureAdded()
feat83.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag36 part,wMat
set feat83=part.Extension.GetLastFeatureAdded()
feat83.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(-0.060053,-0.055,-0.090053),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 elseif getEdgeFromModel(part,createVec3d(-0.060053,-0.055,-0.071),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.012,0.02,""
 End If
part.CreatePlaneFixed2 createVec3d(-0.055,0,0),createVec3d(-0.055,0,-1),createVec3d(-0.055,1,0),1
set feat85=part.Extension.GetLastFeatureAdded()
feat85.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(0,0,-1,0,1,0,1,0,0,-0.055,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag37 part,wMat
set feat85=part.Extension.GetLastFeatureAdded()
feat85.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
end sub

sub codeBag39(part,wMat)
cLn part,wMat,-0.011,0,-0.011,0.0125
cLn part,wMat,-0.011,0.0125,0.07,0.0125
cLn part,wMat,0.07,0.0125,0.07,0
cLn part,wMat,0.07,0,-0.011,0
cCLn part,wMat,0.07,0,-0.011,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag40(part,wMat)
cLn part,wMat,0.03875,0,0.03875,0.0625
cLn part,wMat,0.03875,0.0625,0.07,0.0625
cLn part,wMat,0.07,0.0625,0.07,0
cLn part,wMat,0.07,0,0.03875,0
cCLn part,wMat,0.07,0,0.03875,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag41(part,wMat)
cLn part,wMat,-0.051,0,-0.051,0.00908
cLn part,wMat,-0.051,0.00908,-0.05008,0.01
cLn part,wMat,-0.05008,0.01,-0.016484851290427,0.01
cLn part,wMat,-0.016484851290427,0.01,-0.013724269871963,0.0089952305344106
cArc part,wMat,-0.013724269871963,0.0089952305344106,-0.013597990897719,0.0089613941852408,-0.013467754764469,0.00895
cLn part,wMat,-0.013467754764469,0.00895,-0.01175,0.00895
cArc part,wMat,-0.01175,0.00895,-0.01121966991411,0.0091696699141101,-0.011,0.0097
cLn part,wMat,-0.011,0.0097,-0.011,0.01
cLn part,wMat,-0.011,0.01,-0.01,0.01
cLn part,wMat,-0.01,0.01,-0.01,0
cLn part,wMat,-0.01,0,-0.051,0
cCLn part,wMat,-0.01,0,-0.051,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag42(part,wMat)
cLn part,wMat,-0.067,-0.028,0.0081036297108185,-0.028
cLn part,wMat,0.0081036297108185,-0.028,-0.002,-0.0105
cLn part,wMat,-0.002,-0.0105,-0.011,-0.0105
cLn part,wMat,-0.011,-0.0105,-0.011,-0.0155
cLn part,wMat,-0.011,-0.0155,-0.056,-0.0155
cLn part,wMat,-0.056,-0.0155,-0.056,0.0155
cLn part,wMat,-0.056,0.0155,-0.011,0.0155
cLn part,wMat,-0.011,0.0155,-0.011,0.0105
cLn part,wMat,-0.011,0.0105,-0.002,0.0105
cLn part,wMat,-0.002,0.0105,0.0081036297108184,0.028
cLn part,wMat,0.0081036297108184,0.028,-0.067,0.028
cLn part,wMat,-0.067,0.028,-0.067,-0.028
Part.SketchManager.InsertSketch True
end sub

sub codeBag38(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag39 part,wMat
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag40 part,wMat
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat9=part.Extension.GetLastFeatureAdded()
feat9.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag41 part,wMat
set feat9=part.Extension.GetLastFeatureAdded()
feat9.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,1,6.2831853071796,0,0,1,1,1
 if getEdgeFromModel(part,createVec3d(-0.05008,0.01,0),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.01816,0.037042827935471,""
 elseif getEdgeFromModel(part,createVec3d(-0.016484851290427,0.01,0),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.01816,0.037042827935471,""
 End If
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat11=part.Extension.GetLastFeatureAdded()
feat11.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag42 part,wMat
set feat11=part.Extension.GetLastFeatureAdded()
feat11.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.025,0.025,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
end sub

sub codeBag44(part,wMat)
cLn part,wMat,0,0,0.01495,0
cLn part,wMat,0.01495,0,0.033610254037844,-0.005
cLn part,wMat,0.033610254037844,-0.005,0.01495,-0.01
cLn part,wMat,0.01495,-0.01,0,-0.01
cLn part,wMat,0,-0.01,0,0
cCLn part,wMat,0,-0.01,0,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag45(part,wMat)
cLn part,wMat,-0.06,0.06,-0.06,-0.06
cLn part,wMat,-0.06,-0.06,0.06,-0.06
cLn part,wMat,0.06,-0.06,0.06,0.06
cLn part,wMat,0.06,0.06,-0.06,0.06
cLn part,wMat,-0.015,-0.0086602540378444,0,-0.017320508075689
cLn part,wMat,0,-0.017320508075689,0.015,-0.0086602540378444
cLn part,wMat,0.015,-0.0086602540378444,0.015,0.0086602540378444
cLn part,wMat,0.015,0.0086602540378444,0,0.017320508075689
cLn part,wMat,0,0.017320508075689,-0.015,0.0086602540378444
cLn part,wMat,-0.015,0.0086602540378444,-0.015,-0.0086602540378444
Part.SketchManager.InsertSketch True
end sub

sub codeBag46(part,wMat)
cLn part,wMat,0,0,0.01,0
cLn part,wMat,0.01,0,0.009188,-0.000812
cLn part,wMat,0.009188,-0.000812,0.009188,-0.009188
cLn part,wMat,0.009188,-0.009188,0.01,-0.01
cLn part,wMat,0.01,-0.01,0,-0.01
cLn part,wMat,0,-0.01,0,0
cCLn part,wMat,0,-0.01,0,0
Part.SketchManager.InsertSketch True
end sub

sub codeBag43(part,featMgr)
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag44 part,wMat
set feat4=part.Extension.GetLastFeatureAdded()
feat4.select2 false,0
featMgr.FeatureRevolve 6.2831853071796,0,6.2831853071796,0,0,1,1,1
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,0,-1),1
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,0,-1,0,1,0,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag45 part,wMat
set feat6=part.Extension.GetLastFeatureAdded()
feat6.select2 false,0
featMgr.FeatureCut3 0,0,0,0,0,0.011,0.011,1,1,0,0,0,0,0,0,0,0,0,1,1,false,false,false,0,0,0
part.CreatePlaneFixed2 createVec3d(0,0,0),createVec3d(1,0,0),createVec3d(0,1,0),1
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
part.SketchManager.InsertSketch True
part.BlankRefGeom
Set swActiveMat = Part.SketchManager.ActiveSketch
swSketchMat= createMatFromSWMat(swActiveMat.ModelToSketchXForm)
mSkMat=createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)
wMat=mulMat4x4Mat4x4(swSketchMat,mSkMat)
codeBag46 part,wMat
set feat8=part.Extension.GetLastFeatureAdded()
feat8.select2 false,0
featMgr.FeatureRevolveCut2 6.2831853071796,1,6.2831853071796,0,0,1,1,false,false,false
 if getEdgeFromModel(part,createVec3d(0,-0.000812,-0.009188),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.02,0.01,""
 elseif getEdgeFromModel(part,createVec3d(0,-0.009188,-0.009188),cylEdge) then
   cylEdge.Select(false)
   Part.InsertCosmeticThread 0,0.02,0.01,""
 End If
end sub

sub codeBag47()
createPart0
createPart1
createPart2
end sub

sub codeBag48(part)
set comp = part.AddComponent5 (storePath &"536393 ADN-10-P---(Z).sldprt", 0, "", false, "",0,0,0)
comp.SetXForm(createSWMatFromMat(createMat4x4FromValues(1,0,0,0,1,0,0,0,1,0,0,0)))
set comp = part.AddComponent5 (storePath &"536393 ADN-10-P-A_(KS).sldprt", 0, "", false, "",0,0,0)
comp.SetXForm(createSWMatFromMat(createMat4x4FromValues(0,0,-1,0,-1,0,-1,0,0,0,-8.5725275940315e-18,0)))
set comp = part.AddComponent5 (storePath &"DIN-439-B - M20x1_5(F).sldprt", 0, "", false, "",0,0,0)
comp.SetXForm(createSWMatFromMat(createMat4x4FromValues(1,0,0,0,0,1,0,-1,0,0,-9.1848509936052e-18,0.028)))
end sub

sub codeBag49()
swApp.CloseDoc storePath &"536393 ADN-10-P---(Z).sldprt"
swApp.CloseDoc storePath &"536393 ADN-10-P-A_(KS).sldprt"
swApp.CloseDoc storePath &"DIN-439-B - M20x1_5(F).sldprt"
end sub

sub main
set swApp = Application.SldWorks
code = swApp.RevisionNumber
found = InStr(code, ".")
If (found > 0) Then
  code = Left(code, found-1)
  docVisible=1
  If (CInt(code) >= 18) Then
    docVisible=0
  End If
End If
swApp.SetUserPreferenceToggle 11, FALSE
swApp.SetUserPreferenceToggle 97, FALSE
storePath=BrowseForFolder
If (storePath <> "") Then
   If ((Right(storePath, 1) <> "\") And (Right(storePath, 1) <> "/")) Then
       storePath = storePath + "\"
   End If
   createPart3
End If
end sub
